Import('env')

import pathlib

excluded_modules = [
  "Crypto.Cipher",
  "Crypto.PublicKey",
  "Crypto.Protocol",
  "cryptography",
  "zstandard"
]
exclude_args = " ".join(f"--exclude-module={m}" for m in excluded_modules)

installer_py = File('#system/installer/installer.py')
installer = env.Command('installer/installer', [installer_py], f'pyinstaller {installer_py.abspath} -y --workpath=/data/tmp/build --distpath=/data/tmp/dist {exclude_args}')
